[package]
name = "uurs24"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
petgraph = { version = "0.8.2", features = ["serde", "serde_derive"] }
serde = { version = "1.0", features = ["derive"] }
